Document: ostiary
Title: Debian ostiary Manual
Author: <insert document author here>
Abstract: This manual describes what ostiary is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ostiary/ostiary.sgml.gz

Format: postscript
Files: /usr/share/doc/ostiary/ostiary.ps.gz

Format: text
Files: /usr/share/doc/ostiary/ostiary.text.gz

Format: HTML
Index: /usr/share/doc/ostiary/html/index.html
Files: /usr/share/doc/ostiary/html/*.html
